[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "colosseum"
authors = [{name = "Colosseum @ Northeastern University WIoT", email = "colosseum.neu@gmail.com"}]
dynamic = ["version", "description"]
